version: '3.9'
services:
  teste_DOCKER:
    container_name: teste_DOCKER
    hostname: teste_DOCKER
    image: mysql:8
    restart: always
    command:
      - --authentication-policy=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes:
      - ./teste_DOCKER:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: base_de_dados
      MYSQL_USER: root
      MYSQL_PASSWORD: senha
      TZ: America/Sao_Paulo